# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd451ed7bbb930d06e4297ed1c6a3a511b5dea1a8c92a0b1f3dd1d98bbfe75d1a40f38780e56535b6c56d0c78ce2a408791b26fb143bdc6c2cc3221fe2c725dd

test:
  secret_key_base: da7b94e4eb17d26f73328fdef73ed198491c53ef56cccb9b78b374a1225f5793e66ca73133a4715cc366dc19d26af04a6187624401c9e03dec368b6a80ecdf9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
